import {
  BabyIcon,
  BathtubIcon,
  BedIcon,
  CampfireIcon,
  CarIcon,
  ChefHatIcon,
  CoffeeIcon,
  CookingPotIcon,
  DropIcon,
  FireSimpleIcon,
  GameControllerIcon,
  HandHeartIcon,
  LaptopIcon,
  LightningIcon,
  MountainsIcon,
  MusicNotesIcon,
  PawPrintIcon,
  SnowflakeIcon,
  SunHorizonIcon,
  SwimmingPoolIcon,
  TelevisionIcon,
  TreeIcon,
  UsersThreeIcon,
  WifiHighIcon,
} from "@phosphor-icons/react/dist/ssr";
import type { Icon } from "@phosphor-icons/react";
import type { AmenityKey } from "@/data/types";

export const amenities: Record<AmenityKey, { label: string; icon: Icon }> = {
  pool: { label: "Private pool", icon: SwimmingPoolIcon },
  lawn: { label: "Private lawn", icon: TreeIcon },
  view: { label: "Valley or river view", icon: MountainsIcon },
  terrace: { label: "Terrace", icon: SunHorizonIcon },
  caretaker: { label: "Caretaker on call", icon: HandHeartIcon },
  chef: { label: "Cook on request", icon: ChefHatIcon },
  breakfast: { label: "Breakfast included", icon: CoffeeIcon },
  kitchen: { label: "Equipped kitchen", icon: CookingPotIcon },
  bbq: { label: "Barbecue grill", icon: FireSimpleIcon },
  bonfire: { label: "Bonfire pit", icon: CampfireIcon },
  events: { label: "Space for events", icon: UsersThreeIcon },
  music: { label: "Music system", icon: MusicNotesIcon },
  tv: { label: "Television", icon: TelevisionIcon },
  games: { label: "Games and books", icon: GameControllerIcon },
  kids: { label: "Child-friendly", icon: BabyIcon },
  pets: { label: "Pets welcome", icon: PawPrintIcon },
  wifi: { label: "Wi-Fi", icon: WifiHighIcon },
  ac: { label: "Air-conditioned rooms", icon: SnowflakeIcon },
  power: { label: "Power backup", icon: LightningIcon },
  parking: { label: "Private parking", icon: CarIcon },
  "hot-water": { label: "24-hour hot water", icon: DropIcon },
  workspace: { label: "Work-friendly table", icon: LaptopIcon },
};

export { BathtubIcon, BedIcon, UsersThreeIcon };
